version: '2'
services:
    web:
        build: ./web
        container_name: vicidial
        restart: always
        links:
            - mysql
        ports:
            - 80:80
        depends_on:
            - mysql
    mysql:
        image: mariadb
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=asterisk
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=cron
            - MYSQL_PASSWORD=1234
        ports:
            - 3308:3306
        volumes:
            - ./mysql/data/MySQL_AST_CREATE_tables.sql:/docker-entrypoint-initdb.d/MySQL_AST_CREATE_tables.sql
            - ./mysql/data/sip-iax_phones.sql:/docker-entrypoint-initdb.d/sip-iax_phones.sql
            - ./mysql/data/first_server_install.sql:/docker-entrypoint-initdb.d/first_server_install.sql
        healthcheck:
            test: if [ $$(ps -p 1 -o comm=) = "mysqld" ]; then exit 0; else exit 1; fi
            interval: 5s
            retries: 400


