version: '3'
services:
    web:
        build: 
            context: ./web
            args:
                VICIDIAL_DB_HOST: mysql
                VICIDIAL_DB_NAME: asterisk
                VICIDIAL_DB_USER: root
                VICIDIAL_DB_PASSWORD: root
                VICIDIAL_DB_CUSTOM_USER: cron
                VICIDIAL_DB_CUSTOM_PASSWORD: 1234
        container_name: vicidial
        restart: always
        ports:
            - 80:80
        links:
            - mysql
        depends_on:
            - mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8080:80           
    mysql:
        image: mariadb
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=asterisk
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=cron
            - MYSQL_PASSWORD=1234
        ports:
            - 3308:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/import/MySQL_AST_CREATE_tables.sql:/docker-entrypoint-initdb.d/MySQL_AST_CREATE_tables.sql
            - ./mysql/import/first_server_install.sql:/docker-entrypoint-initdb.d/first_server_install.sql
        healthcheck:
            test: if [ $$(ps -p 1 -o comm=) = "mysqld" ]; then exit 0; else exit 1; fi
            interval: 5s
            retries: 400