version: '2'
services:
    web:
        build: ./web
        container_name: vicidial
        restart: always
        links:
            - mysql
        ports:
            - 80:80
        depends_on:
            - mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=asterisk
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=cron
            - MYSQL_PASSWORD=1234
        ports:
            - 3306:3306
