version: '3'
services:
    asterisk:
        build:
            context: ./asterisk
            args:
                ASTERISK_SERVER_IP: 192.168.0.210
                DB_HOST: mysql
                DB_NAME: asterisk
                DB_USER: root
                DB_PASSWORD: root
                DB_CUSTOM_USER: cron
                DB_CUSTOM_PASSWORD: 1234
                FTP_HOST: 127.0.0.1
                FTP_USER: root
                FTP_PASS: root
        cap_add:
            - SYS_TIME
            - SYS_NICE
        container_name: asterisk
        restart: always
        dns:
            - 8.8.8.8
        volumes:
            - ./asterisk/config:/etc/asterisk
        ports:
            - "5060:5060/udp"
            - "5060:5060/tcp"
        links:
            - mysql
        depends_on:
            - mysql
    web:
        build:
            context: ./web
            args:
                VICIDIAL_DB_HOST: mysql
                VICIDIAL_DB_NAME: asterisk
                VICIDIAL_DB_USER: root
                VICIDIAL_DB_PASSWORD: root
                VICIDIAL_DB_CUSTOM_USER: cron
                VICIDIAL_DB_CUSTOM_PASSWORD: 1234
        cap_add:
            - SYS_TIME
            - SYS_NICE
        container_name: vicidial
        restart: always
        volumes:
            - ./mysql/logs/vicidial_mysqli_errors.txt:/var/www/localhost/htdocs/agc/vicidial_mysqli_errors.txt
        ports:
            - 80:80
        links:
            - mysql
        depends_on:
            - mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8080:80
    mysql:
        build:
            context: ./mysql
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=asterisk
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=cron
            - MYSQL_PASSWORD=1234
            - TZ=Europe/Paris
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/import:/docker-entrypoint-initdb.d
